name: Release
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint_pr_title:
    name: Lint PR title
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Lint title
        run: npx --no-install commitlint <<< "${{ github.event.pull_request.title }}"
